# -*- coding: utf-8 -*-
"""cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ObiLdW1pQlNU5LUTTSj1Ts2g11bZ0w_j
"""

import pandas as pd
import numpy as np
from pandas import read_csv
from math import isnan

from google.colab import drive
drive.mount('/content/drive')

file_name = '/content/drive/MyDrive/Uni/Mineria de datos/renamed.csv'
df = read_csv(file_name, header=0, delimiter=',')

df

df.describe()

df.replace(-999999.0, np.nan, inplace=True)
-999999.0 in df

df['inp_b_7da'] = df['inp_b_7da'].apply(lambda x: np.nan if x < 0 else x)
df['a_adult_inp_b_occ_7da'] = df['a_adult_inp_b_occ_7da'].apply(lambda x: np.nan if x < 0 else x)
df['inp_b_u_7da'] = df['inp_b_u_7da'].apply(lambda x: np.nan if x < 0 else x)
df['icu_b_u_7da'] = df['icu_b_u_7da'].apply(lambda x: np.nan if x < 0 else x)
df['staff_adult_icu_b_occ_7da'] = df['staff_adult_icu_b_occ_7da'].apply(lambda x: np.nan if x < 0 else x)
df['pda_adult_conf_7ds'] = df['pda_adult_conf_7ds'].apply(lambda x: np.nan if x < 0 else x)
df['pda_adult_sus_7ds'] = df['pda_adult_sus_7ds'].apply(lambda x: np.nan if x < 0 else x)

df.describe()

# we replace "total beds 7 day avg" with the avg col
df['t_b_7da'].fillna(df['t_b_7da'].mean(), inplace=True)
# we replace "inpatient beds 7 day avg" with the avg col
df['inp_b_7da'].fillna(df['inp_b_7da'].mean(), inplace=True)

'''df['a_adult_b_7da'].fillna(df['a_adult_b_7da'].mean(), inplace=True)
df['a_adult_inp_b_7da'].fillna(df['a_adult_inp_b_7da'].mean(), inplace=True)
df['inp_b_u_7da'].fillna(df['inp_b_u_7da'].mean(), inplace=True)
df['a_adult_inp_b_occ_7da'].fillna(df['a_adult_inp_b_occ_7da'].mean(), inplace=True)
df['t_adult_h_conf_sus_7da'].fillna(df['t_adult_h_conf_sus_7da'].mean(), inplace=True)
df['t_adult_h_conf_7da'].fillna(df['t_adult_h_conf_7da'].mean(), inplace=True)
df['t_ped_h_conf_sus_7da'].fillna(df['t_ped_h_conf_sus_7da'].mean(), inplace=True)
df['t_ped_h_conf_7da'].fillna(df['t_ped_h_conf_7da'].mean(), inplace=True)
df['t_icu_b_7da'].fillna(df['t_icu_b_7da'].mean(), inplace=True)
df['t_staff_adult_icu_b_7da'].fillna(df['t_staff_adult_icu_b_7da'].mean(), inplace=True)
df['icu_b_u_7da'].fillna(df['icu_b_u_7da'].mean(), inplace=True)
df['staff_adult_icu_b_occ_7da'].fillna(df['staff_adult_icu_b_occ_7da'].mean(), inplace=True)
df['staff_adult_icu_conf_sus_7da'].fillna(df['staff_adult_icu_conf_sus_7da'].mean(), inplace=True)
df['staff_adult_icu_conf_7da'].fillna(df['staff_adult_icu_conf_7da'].mean(), inplace=True)
df['t_staff_adult_icu_b_7da'].fillna(df['t_staff_adult_icu_b_7da'].mean(), inplace=True)
df['pda_adult_conf_7ds'].fillna(df['pda_adult_conf_7ds'].mean(), inplace=True)
df['pda_adult_sus_7ds'].fillna(df['pda_adult_sus_7ds'].mean(), inplace=True)'''

df

df[df.city.isna()]

df.city[0] = 'Elmendorf AFB'
df.city[2] = 'Vieques'
df.city[4] = 'Metairie'
df.city[8] = 'Vieques'

df[df.fips_code.isna()]

df.fips_code[0] = '07450'
df.fips_code[1] = '29940'
df.fips_code[2] = '72147'
df.fips_code[3] = '72097'
df.fips_code[4] = '22051'
df.fips_code[5] = '51510'
df.fips_code[6] = '72127'
df.fips_code[7] = '37650'
df.fips_code[8] = '72147'
df.fips_code[9] = '99703'

df.to_csv('no_nans_with_avgs.csv')
from google.colab import files
files.download('no_nans_with_avgs.csv')

df.isna().any()