#Retrieve the data saved AFTER the profiling practice...... this means data already cleaned

setwd("C:/Users/Javier MSi/Desktop/UPC/Q7/MD/Trabajo")
dd <- read.csv("DATASET_ENTREGA_3_DEFINITIU.csv", sep=",");
names(dd)
dim(dd)
summary(dd)

for(i in 1:ncol(dd)){
  if(is.character(dd[,i])){
    dd[,i]<-as.factor(dd[,i])
  }
  if(is.logical(dd[,i])){
    dd[,i]<-as.factor(dd[,i])
  }
}

attach(dd)

sapply(dd,class)
#set a list of numerical variables
names(dd)


library(cluster)

#do not include in actives the identifier variables nor the potential response variable

actives<-c(1,3:29)
dissimMatrix <- daisy(dd[,actives], metric = "gower", stand=TRUE)

distMatrix<-dissimMatrix^2

h1 <- hclust(distMatrix,method="ward.D2")  # NOTICE THE COST
#versions noves "ward.D" i abans de plot: par(mar=rep(2,4)) si se quejara de los margenes del plot

plot(h1)

k<-3

c2 <- cutree(h1,k)

#class sizes 
table(c2)

#comparing with other partitions
#table(c1,c2)

# LETS SEE THE PARTITION VISUALLY

c1<-c2

plot(pda_adult_conf_7ds,icu_b_u_7da)
plot(t_adult_h_conf_sus_7da,icu_b_u_7da_perc,col=c1,main="Clustering of Hospital data in 3 classes")

pairs(dd[,10:20], col=c1)

#INDIVIDUAL PLOTS
plot(inp_b_u_7da,a_adult_inp_b_occ_7da,col=c1)
plot(inp_b_u_7da,icu_b_u_7da,col=c1)