# -*- coding: utf-8 -*-
"""delete_rows_with_NaN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11hs1asudxuQT5Voyn1ToiKCSxvkVs9wR
"""

import pandas as pd
import numpy as np
from pandas import read_csv
from math import isnan

from google.colab import drive
drive.mount('/content/drive')

FILE = '/content/drive/MyDrive/COLLEGE/Mineria de datos/Definitiu_07_08_2020.csv'
df = read_csv(FILE, header=0, delimiter=';')

df.isna().sum()

nans = df.isna().sum(axis=1).tolist()
print(len(df.columns))
nans_dict = {}
for i in range(len(nans)):
  nans_dict[i] = nans[i]

sorted_rows = {k: v for k, v in sorted(nans_dict.items(), key=lambda item: item[1], reverse=True)}

total = [k for k, v in sorted_rows.items() if v >= 12]
len(total)
total[:10]

clean_df = df.drop(df.index[total])

nans = clean_df.isna().sum(axis=1).tolist()
nans_dict = {}
for i in range(len(nans)):
  nans_dict[i] = nans[i]

sorted_rows = {k: v for k, v in sorted(nans_dict.items(), key=lambda item: item[1], reverse=True)}
sorted_rows

clean_df.to_csv('df_with_deleted_rows.csv')
from google.colab import files
files.download('df_with_deleted_rows.csv')

# alguna columna numerica que no tenga missings?

clean_df.isna().sum(axis = 0)