# -*- coding: utf-8 -*-
"""metadata_file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13U2rhdX26qoJZtVFDzMEnCGA8vPJvBSa
"""

import pandas as pd
import numpy as np
from pandas import read_csv
from math import isnan

file_name = '/content/drive/MyDrive/COLLEGE/Mineria de datos/df_with_new_vars.csv'
df = read_csv(file_name, header=0, delimiter=',')

from google.colab import drive
drive.mount('/content/drive')

df.describe()

def is_nan(x):
  if type(x) == str and x != '':
    return False
  if x == -999999.0 or isnan(x) or x != x:
    return True
  return False

info = {}
for col in df.columns:
  s = df[col].map(is_nan)
  c = df[col].value_counts()
  if len(c) >= 100:
    c = 'non_cat'
  info[col] = c

info

for col in df.columns:
  try:
    min = df[col].min()
    max = df[col].max()
    print(f'{col} [{min}, {max}] \n')
  except:
    pass

df.to_csv('dataset_renamed_column.csv')
from google.colab import files
files.download('dataset_renamed_column.csv')