# -*- coding: utf-8 -*-
"""missing_values.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14GzXTUQTklkQ3oMlxKuflbg0_1BuSEpw
"""

import pandas as pd
import numpy as np
from pandas import read_csv
from math import isnan

file_name = 'COVID-19_Reported_Patient_Impact_and_Hospital_Capacity_by_Facility_1_per_hospital_CUTTED.csv'
df = read_csv(file_name, header=0, delimiter=';')

len(df.columns)

df.describe()

def is_nan(x):
  if type(x) == str and x != '':
    return False
  if x == -999999.0 or isnan(x) or x != x:
    return True
  return False

nans = {}
total_rows = 0
total_miss = 0
for col in df.columns:
  s = df[col].map(is_nan)
  col_len = len(s)
  col_nans = len(s[s == True].index) #(df[col].map(is_nan)).count()
  nans[col] = (round(col_nans/col_len*100, 2), col_nans)
  total_rows += col_len
  total_miss += col_nans
  #print(df[col].map(is_nan).value_counts())

print(total_rows)
print(total_miss)
print(total_miss/total_rows)

# convert total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum to binary
df['total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum (USAR COMO BINARIA)'] = df['total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum (USAR COMO BINARIA)'].map(lambda x: False if x<=0 else True)
df.rename(columns={'total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum (USAR COMO BINARIA)': 'there_are_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day'}, inplace=True)

df['there_are_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day'].value_counts()

df.to_csv('dataset_renamed_column.csv')
from google.colab import files
files.download('dataset_renamed_column.csv')

from google.colab import drive
drive.mount('/content/drive')

file_name_nuevo = '/content/drive/MyDrive/Mineria de datos/non_negative.csv'
df_new = read_csv(file_name_nuevo, header=0, delimiter=';')

def how_many()