# -*- coding: utf-8 -*-
"""New_Variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ajiJV3nRlWZLAzwgX1tbQYJjZ1eRCHYw
"""

import pandas as pd
import numpy as np
from pandas import read_csv
from math import isnan

from google.colab import drive
drive.mount('/content/drive')

import matplotlib.pyplot as plt

FILE = '/content/drive/MyDrive/Mineria de datos/KNN_DONE_NO_NULLS.csv'
df = read_csv(FILE, header=0, delimiter=',')

df.isna().sum()

nans = df.isna().sum(axis=1).tolist()
print(len(df.columns))
nans_dict = {}
for i in range(len(nans)):
  nans_dict[i] = nans[i]
sorted_rows = {k: v for k, v in sorted(nans_dict.items(), key=lambda item: item[1], reverse=True)}

total = [k for k, v in sorted_rows.items() if v >= 12]
len(total)
total[:10]

clean_df = df.drop(df.index[total])

nans = clean_df.isna().sum(axis=1).tolist()
nans_dict = {}
for i in range(len(nans)):
  nans_dict[i] = nans[i]

sorted_rows = {k: v for k, v in sorted(nans_dict.items(), key=lambda item: item[1], reverse=True)}
sorted_rows

clean_df.to_csv('df_with_deleted_rows.csv')
from google.colab import files
files.download('df_with_deleted_rows.csv')

# alguna columna numerica que no tenga missings?

clean_df.isna().sum(axis = 0)

df

(df['inp_b_7da'][130:140] == 0.0)
# print(df['inp_b_7da'][136])
# print(df['inp_b_u_7da'][138])
# print((df['inp_b_7da'] == 0).sum(axis=0))

df['inp_b_7da'].replace(0, -1, inplace = True)
df['inp_b_u_7da_perc'] = (df['inp_b_u_7da']/df['inp_b_7da'])*100
df['inp_b_u_7da_perc'] = np.where(df['inp_b_u_7da_perc'] <= 0, 0, df['inp_b_u_7da_perc'])
df['inp_b_7da'].replace(-1, 0, inplace = True)
df.hist(column = 'inp_b_u_7da_perc')
df['inp_b_u_7da_perc'] = df['inp_b_u_7da_perc'].round(1)

df

df['t_icu_b_7da'].replace(0, -1, inplace = True)
df['icu_b_u_7da_perc'] = (df['icu_b_u_7da']/df['t_icu_b_7da'])*100
df['icu_b_u_7da_perc'] = np.where(df['icu_b_u_7da_perc'] <= 0, 0, df['icu_b_u_7da_perc'])
df['t_icu_b_7da'].replace(-1, 0, inplace = True)
df.hist(column = 'icu_b_u_7da_perc')
df['icu_b_u_7da_perc'] = df['icu_b_u_7da_perc'].round(1)

df

df['t_adult_h_conf_sus_7da'].replace(0, -1, inplace = True)
df['t_adult_h_conf_7da_perc'] = (df['t_adult_h_conf_7da']/df['t_adult_h_conf_sus_7da'])*100
df['t_adult_h_conf_7da_perc'] = np.where(df['t_adult_h_conf_7da_perc'] <= 0, 0, df['t_adult_h_conf_7da_perc'])
df['t_adult_h_conf_sus_7da'].replace(-1, 0, inplace = True)
df.hist(column = 't_adult_h_conf_7da_perc')
df['t_adult_h_conf_7da_perc'] = df['t_adult_h_conf_7da_perc'].round(1)

df

df.to_csv('df_with_new_vars.csv', index = False)
from google.colab import files
files.download('df_with_new_vars.csv')