# -*- coding: utf-8 -*-
"""OutliersExtremos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KaiRY3n5lqtJ7kj2MlvM1oFlbUP4jvCd
"""

#%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from collections import Counter
from IPython.core.interactiveshell import InteractiveShell
import warnings


InteractiveShell.ast_node_interactivity = "all"
pd.set_option('precision', 3)
sns.set()
warnings.filterwarnings('ignore')

# extra imports
from pandas import read_csv
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import LocalOutlierFactor
from sklearn import preprocessing
from statsmodels.genmod.generalized_linear_model import GLM
from pandas.plotting import scatter_matrix
from scipy.stats import boxcox

Tabla = read_csv("/content/no_nans_with_avgs.csv", header = 0, delimiter = ",")

"""

---

"""

Tabla.head()

"""

---

"""

Tabla[Tabla.a_adult_b_7da > 2000]

Tabla[Tabla.a_adult_inp_b_7da > 2000]

Tabla[Tabla.a_adult_inp_b_occ_7da > 1500]

Tabla[Tabla.icu_b_u_7da > 300]

Tabla[Tabla.inp_b_7da > 2500]

Tabla[Tabla.inp_b_u_7da > 1500]

Tabla[Tabla.pda_adult_conf_7ds > 300]

Tabla[Tabla.pda_adult_sus_7ds > 2000]

Tabla[Tabla.staff_adult_icu_b_occ_7da > 200]

Tabla[Tabla.staff_adult_icu_conf_7da > 130]

Tabla[Tabla.staff_adult_icu_conf_sus_7da > 180]

Tabla[Tabla.t_adult_h_conf_7da > 300]

Tabla[Tabla.t_adult_h_conf_sus_7da > 800]

Tabla[Tabla.t_b_7da > 4000]

Tabla[Tabla.t_icu_b_7da > 400]

Tabla[Tabla.t_ped_h_conf_7da > 40]

Tabla[Tabla.t_ped_h_conf_sus_7da > 60]

Tabla[Tabla.t_staff_adult_icu_b_7da > 250]