# -*- coding: utf-8 -*-
"""renaming.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TElXhIjYYZuUM_YL-GbCgtPA1HFHjQRl
"""

import pandas as pd
import numpy as np
from pandas import read_csv
from math import isnan

from google.colab import drive
drive.mount('/content/drive')

file_name = '/content/drive/MyDrive/Uni/Mineria de datos/df_with_deleted_rows.csv'
df = read_csv(file_name, header=0, delimiter=',')

df.describe()

df

df.columns.values

df = df.rename(columns={'is_metro_micro' : 'metro',
                   'total_beds_7_day_avg' : 't_b_7da',
                   'all_adult_hospital_beds_7_day_avg' : 'a_adult_b_7da',
                   'all_adult_hospital_inpatient_beds_7_day_avg' : 'a_adult_inp_b_7da',
                   'inpatient_beds_used_7_day_avg' : 'inp_b_u_7da',
                   'all_adult_hospital_inpatient_bed_occupied_7_day_avg' : 'a_adult_inp_b_occ_7da',
                   'total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg' : 't_adult_h_conf_sus_7da',
                   'total_adult_patients_hospitalized_confirmed_covid_7_day_avg' : 't_adult_h_conf_7da',
                   'total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg' : 't_ped_h_conf_sus_7da',
                   'total_pediatric_patients_hospitalized_confirmed_covid_7_day_avg' : 't_ped_h_conf_7da',
                   'inpatient_beds_7_day_avg' : 'inp_b_7da', 
                   'total_icu_beds_7_day_avg' : 't_icu_b_7da',
                   'total_staffed_adult_icu_beds_7_day_avg' : 't_staff_adult_icu_b_7da',
                   'icu_beds_used_7_day_avg' : 'icu_b_u_7da',
                   'staffed_adult_icu_bed_occupancy_7_day_avg' : 'staff_adult_icu_b_occ_7da',
                   'staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_avg' : 'staff_adult_icu_conf_sus_7da',
                   'staffed_icu_adult_patients_confirmed_covid_7_day_avg' : 'staff_adult_icu_conf_7da',
                   'there_are_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day' : 'are_ped_h_conf_sus_7da',
                   'previous_day_admission_adult_covid_confirmed_7_day_sum' : 'pda_adult_conf_7ds',
                   'previous_day_admission_adult_covid_suspected_7_day_sum' : 'pda_adult_sus_7ds'});

df

df.to_csv('renamed.csv')
from google.colab import files
files.download('renamed.csv')